import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { StarBackground } from "@/components/effects/star-background";
import { LanguageProvider } from "@/contexts/language-provider";
import { SecureKeyProvider } from "@/contexts/secure-key-context";
import { OfflineStatusToast } from "@/components/ui/offline-indicator";
import { registerServiceWorker } from "@/lib/register-sw";
import { AnalyticsProvider } from "@/components/ui/analytics-provider";
import { ErrorBoundary } from "@/components/ui/error-boundary";
import { PrivacyConsentBanner } from "@/components/ui/privacy-consent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Galaxy Smart Wallet",
  description: "Generated by Create Next App",
  icons: {
    icon: "/galaxy-smart-wallet-logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Registrar service worker en el cliente
  if (typeof window !== 'undefined') {
    registerServiceWorker();
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative bg-[#0A0B1E] text-white`}
        suppressHydrationWarning={true}
      >
        <ErrorBoundary>
          <SecureKeyProvider>
            <AnalyticsProvider>
              <LanguageProvider>
                <StarBackground />
                <main className="relative z-10">{children}</main>
                <OfflineStatusToast />
                <PrivacyConsentBanner />
              </LanguageProvider>
            </AnalyticsProvider>
          </SecureKeyProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
