name: Bug Report 🐛
description: Report unexpected behavior or application errors
title: "[BUG] "
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report

        Please complete the following form to help us reproduce and fix the issue quickly.

  - type: input
    id: title
    attributes:
      label: 📝 Title
      description: A short and clear title for the issue
      placeholder: "e.g., Login fails with WalletConnect"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 🔍 Description
      description: Please describe the issue in detail
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the issue
      placeholder: |
        1. Go to...
        2. Click on...
        3. See the error...
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: 👌🏼 Expected Behavior
      description: What did you expect to happen?
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: ✅ Actual Behavior
      description: What actually happened instead?
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: 🖥️ Environment
      description: OS, browser, app version, or anything relevant
      placeholder: "e.g., Windows 11, Chrome 125, Galaxy_KJ v1.0"

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots / Logs
      description: Attach screenshots or logs if applicable

  - type: textarea
    id: extra
    attributes:
      label: 📚 Additional Information
      description: Anything else that might help

  - type: input
    id: eta
    attributes:
      label: ⏳ ETA
      description: Estimated time to resolve this (optional)
