blank_issues_enabled: false
contact_links:
  - name: 💬 Questions or General Support
    url: https://github.com/Galaxy-KJ/dApp-Galaxy_KJ/discussions
    about: Please use Discussions for general feedback, help, or ideas that are not bugs or features.
